language: php

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.3
      env: WP_VERSION=4.4

before_script:
  - composer self-update --no-interaction
  - composer install --no-interaction
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpunit
  - vendor/bin/phpcs --standard=phpcs.xml
